### ISSUE TITLE
Not cryptographically secure

### ISSUE THREAD

**Issue by joepie91** [elcodedocle/cryptosecureprng#2]
[This code](https://github.com/elcodedocle/cryptosecureprng/blob/master/CryptoSecurePRNG.php#L191-L198) makes this library not (guaranteed) cryptographically secure. `mt_rand` is never acceptable in a CSPRNG, no matter the circumstances.

The correct course of action is to throw an exception if no suitable random source is present, and force the developer/user to fix their broken environment.

**Comment by paragonie-scott** [comment]
For example: [random_compat's fallback is not mt_rand()](https://github.com/paragonie/random_compat/blob/681c500c1773ac856385d3d732e4fc59394d1f18/lib/random.php#L67-L78).

**Comment by elcodedocle** [comment]
fixed by 4036d1d62dd289a87c9e7782d868b4b7d7bbc7c2

**Comment by joepie91** [comment]
Excellent, thanks :)

**Comment by elcodedocle** [comment]
Thanks to you for bringing the issue to my attention :-) And thanks a lot to @paragonie-scott for introducing me the [random_compat](https://github.com/paragonie/random_compat) project. Really useful lib, will definitely recommend it!
